---
# tasks file for http
- name: install nginx
  apt:
          name: nginx
          state: present
          update_cache: yes

- name: nginx conf template
  template:
          src: templates/nginx.conf.j2
          dest: /etc/nginx/sites-available/default

- name: start nginx
  ansible.builtin.sysvinit:
          name: nginx
          state: started

