---
- hosts: localhost
  gather_facts: true
  tasks:
          - name: create user1
            user:
                    name: user1
                    password: d8578edf8458ce06fbc5bb76a58c5ca4
                    shell: /bin/bash
                    groups: sudo
                    append: yes
          - name: create ssh-key
            user:
                    name: user1
                    generate_ssh_key: yes
                    ssh_key_file: .ssh/id_rsa
          - name: istall authorized key
            authorized_key:
                    user: user1
                    state: present
                    key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
