---
- name: Install dnsmasq
  apt:
          name: dnsmasq
          state: present
- name: set conf
  template:
          src: etc_dnsmasq.conf.j2
          dest: /etc/dnsmasq.conf
          validate: 'dnsmasq --test --conf-file=%s'          
  notify: restart_dnsmasq

- name: start dnsmasq
  ansible.builtin.sysvinit:
          name: dnsmasq
          state: started
