---
# tasks file for php
- name: install php-fpm
  apt:
          name: php-fpm
          state: present
          update_cache: yes

- name: fpm config
  ansible.builtin.lineinfile:
          dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
          regexp: "^listen ="
          line: "listen = 9000"

- name: start php-fpm
  ansible.builtin.sysvinit:
          name: "php{{ php_version }}-fpm"
          state: started
